include: "../tools/project_structure.smk"
include: "../tools/download.smk"
include: "../tools/compute.smk"
include: "../tools/compress.smk"

PLOT_SCRIPT = "plot_kmers_in_superstring.py"
PLOT_FORMATS = ["png"]

DATASETS = [
    "S._Pneumoniae_pangenome",
    # "SARS-CoV-2_pangenome",
    # "E._coli_pangenome",
]
KS = [15, 31, 63]
RSPSS_METHODS = [
    "eulertigs",
    "matchtigs",
]
MS_METHODS = [
    "greedy-maxone", # superstrings are all the same for "greedy"
] + [
    f"pareto-{run_penalty}" for run_penalty in [1, 8, 32, 128, 256, 512]
]

rule all:
    input:
        expand(f"{RESULTS}/{{dataset}}/plot-{{k}}.{{plot_format}}", dataset = DATASETS, k = KS, plot_format = PLOT_FORMATS)

rule plot_distinct_kmer_counts_in_superstrings:
    priority: 3
    input:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    output:
        f"{RESULTS}/{{dataset}}/plot-{{k}}.{{plot_format}}"
    wildcard_constraints:
        k = "\\d+"
    shell:
        f"""
            ./{PLOT_SCRIPT} {{input}} {{wildcards.k}} {{wildcards.plot_format}}
        """

rule compute_kmer_counts_in_superstrings:
    input:
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.kmer_count.txt" for method in RSPSS_METHODS + MS_METHODS],
         f"{SUPERSTRINGS}/{{dataset}}/{{k}}/kmer_count.txt"
    output:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    shell:
        f"""
            mkdir -p $(dirname {{output}})

            # Format: method, kmer count in superstring

            for method in {" ".join(RSPSS_METHODS + MS_METHODS)}; do
                printf "%s\t%d\n" "$method" \
                    $(head -n 1 {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".kmer_count.txt) \
                    >> {{output}}.tmp
            done
            printf "%s\t%d\n" "kmer_count" $(head -n 1 {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/kmer_count.txt) >> {{output}}.tmp

            echo "method\tdistinct kmers in the mask" > {{output}}
            sort {{output}}.tmp >> {{output}}
            rm {{output}}.tmp
        """
