include: "../tools/project_structure.smk"
include: "../tools/download.smk"
include: "../tools/compute.smk"
include: "../tools/compress.smk"
include: "../tools/test.smk"

PLOT_SCRIPT = "plot_compressed_sizes.py"
PLOT_FORMATS = ["png"]

DATASETS = [
    "S._Pneumoniae_pangenome",
    # "SARS-CoV-2_pangenome",
    # "E._coli_pangenome",
]
KS = [31, 63]
RSPSS_METHODS = [
    "eulertigs",
    "matchtigs",
]
MS_METHODS = [
    "greedy-maxone",
    "greedy-minrun",
] + [
    f"pareto-{run_penalty}" for run_penalty in [1, 8, 32, 128, 256, 512]
]
# Baseline method: essCompress

rule all:
    input:
        expand(f"{RESULTS}/{{dataset}}/plot-{{k}}.{{plot_format}}", dataset = DATASETS, k = KS, plot_format = PLOT_FORMATS),
        expand(f"{RESULTS}/{{dataset}}/plot-{{k}}-best.{{plot_format}}", dataset = DATASETS, k = KS, plot_format = PLOT_FORMATS)

rule plot_compressed_sizes:
    priority: 3
    input:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    output:
        f"{RESULTS}/{{dataset}}/plot-{{k}}.{{plot_format}}",
        f"{RESULTS}/{{dataset}}/plot-{{k}}-best.{{plot_format}}"
    wildcard_constraints:
        k = "\\d+"
    shell:
        f"""
            ./{PLOT_SCRIPT} {{input}} {{wildcards.k}} {{wildcards.plot_format}}
        """

rule compute_compressed_sizes:
    """
    # COMPRESION PROTOCOLS - CURRENT
    everything:
        xz_9, xz_9 (MS -- mask, RPSS -- lengths of runs of ones + k)
        xz_max, bzip2_best
        geco3_l5, geco3_l5
        geco3_max, geco3_max

    # COMPRESION PROTOCOLS - OLD
    #   a) rspss: (name, compr_superstring, compr_seqlens)
    ("std-basic", "xz_9", "xz_9"),
    ("std-max",    "xz_max", "xz_9"),
    ("geco-basic", "geco3_l5", "xz_9"),
    ("geco-max",   "geco3_max", "xz_9")

    # COMPRESION PROTOCOLS FOR MASKED SUPERSTRINGS - OLD
    #    b) masked superstrings: (name, compr_superstring, compr_mask)
    ("std-basic", "xz_9", "bz2_best"),
    ("std-max", "xz_max", "bz2_best"),
    ("geco-basic", "geco3_l5", "geco3_l5"),
    ("geco-max", "geco3_max", "geco3_max")
    """
    input:
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.xz"     for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.xz.max" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.co"     for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.co.max" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.lengths.xz" for method in RSPSS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.xz"      for method in MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.bz2"     for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.co"      for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.co.max"  for method in RSPSS_METHODS + MS_METHODS],
         f"{SUPERSTRINGS}/{{dataset}}/{{k}}/essCompress.essc", # Baseline method
         f"{SUPERSTRINGS}/{{dataset}}/{{k}}/kmer_count.txt",
        # Check that computed and compressed representations contain the same k-mer sets
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.fa.no-comp.check" for method in MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.fa.de-co.check" for method in MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.fa.de-co.max.check" for method in MS_METHODS]
    output:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    shell:
        f"""
            mkdir -p $(dirname {{output}})

            for method in {" ".join(RSPSS_METHODS)}; do
                printf "%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n" \
                    "$method" \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.xz) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.lengths.xz) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.xz.max) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.bz2) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.co) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.co) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.co.max) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.co.max) \
                    >> {{output}}.tmp
            done

            for method in {" ".join(MS_METHODS)}; do
                printf "%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n" \
                    "$method" \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.xz) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.xz) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.xz.max) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.bz2) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.co) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.co) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.co.max) \
                    $(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.co.max) \
                    >> {{output}}.tmp
            done

            KMER_COUNT=$(cat {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/kmer_count.txt)
            printf "%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n" "kmer_count" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" "$KMER_COUNT" >> {{output}}.tmp

            BASELINE_SIZE=$(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/essCompress.essc)
            printf "%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\n" "essCompress" "$BASELINE_SIZE" 0 "$BASELINE_SIZE" 0 "$BASELINE_SIZE" 0 "$BASELINE_SIZE" 0 >> {{output}}.tmp

            echo "method\tsuperstring_std_basic\tmask_std_basic\tsuperstring_std_max\tmask_std_max\tsuperstring_geco_basic\tmask_geco_basic\tsuperstring_geco_max\tmask_geco_max" > {{output}}
            sort {{output}}.tmp >> {{output}}
            rm {{output}}.tmp
        """
