include: "../tools/project_structure.smk"
include: "../tools/download.smk"
include: "../tools/compute.smk"
include: "../tools/compress.smk"

DATASETS = [
    "S._Pneumoniae_pangenome",
    # "SARS-CoV-2_pangenome",
    # "E._coli_pangenome",
]
KS = [15, 31, 63]
RSPSS_METHODS = [
    "eulertigs",
    "matchtigs",
]
MS_METHODS = [
    "greedy-maxone", # superstrings are all the same for "greedy"
] + [
    f"pareto-{run_penalty}" for run_penalty in [1, 8, 32, 128, 256, 512]
]

rule all:
    input:
        expand(f"{RESULTS}/{{dataset}}/{{k}}.tsv", dataset = DATASETS, k = KS)

rule compute_bits_per_character_data:
    input:
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.co.max" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring.xz.max" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring" for method in RSPSS_METHODS + MS_METHODS],
    output:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    shell:
        f"""
            mkdir -p $(dirname {{output}})

            # Format: method, superstring length, compressed size GECO, compressed size XZ

            for method in {" ".join(RSPSS_METHODS + MS_METHODS)}; do
                LENGTH="$(tail -n +2 {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".fa | wc -m)"
                SIZE_GECO="$(echo "$(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.co.max) * 8" | bc)"
                SIZE_XZ="$(echo   "$(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring.xz.max) * 8" | bc)"
                printf "%s\t%d\t%d\t%d\n" "$method" "$LENGTH" "$SIZE_GECO" "$SIZE_XZ" >> {{output}}.tmp
            done

            echo "method\tlength\tcompressed size geco\tcompressed size xz" > {{output}}
            sort {{output}}.tmp >> {{output}}
            rm {{output}}.tmp
        """
