include: "../tools/project_structure.smk"
include: "../tools/download.smk"
include: "../tools/compute.smk"
include: "../tools/compress.smk"

DATASETS = [
    "S._Pneumoniae_pangenome",
    # "SARS-CoV-2_pangenome",
    # "E._coli_pangenome",
]
KS = [15, 31]
RSPSS_METHODS = [
    "eulertigs",
    "matchtigs",
]
MS_METHODS = [
    "greedy-minone",
    "greedy-maxone",
    "greedy-minrun",
] + [
    f"pareto-{run_penalty}" for run_penalty in [1, 8, 32, 128, 256, 512]
]
COUNT_METHODS = [
    "lowerbound_length",
    "lowerbound_matchtig_count",
    "kmer_count",
]

rule all:
    input:
        expand(f"{RESULTS}/{{dataset}}/{{k}}.tsv", dataset = DATASETS, k = KS)

rule compute_compressed_sizes:
    input:
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.superstring" for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.mask.efe"    for method in RSPSS_METHODS + MS_METHODS],
        [f"{SUPERSTRINGS}/{{dataset}}/{{k}}/{method}.txt" for method in COUNT_METHODS]
    output:
        f"{RESULTS}/{{dataset}}/{{k}}.tsv"
    shell:
        f"""
            mkdir -p $(dirname {{output}})

            # Format: method, superstring length, Elias-Fano encoded mask length
            # We consider 2 bits per character of superstring and mask encoded by Elias-Fano encoding in binary format.
            # RPSS methods only need to encode ends of runs of ones, but also need to store k, this is simulated by adding one byte (+8 bits).

            for method in {" ".join(RSPSS_METHODS)}; do
                printf "%s\t%d\t%d\n" "$method" \
                    $(echo "$(cat {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring | wc -c) * 2" | bc) \
                    $(echo "$(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.efe) * 8 + 8" | bc ) \
                    >> {{output}}.tmp
            done
            for method in {" ".join(MS_METHODS)}; do
                printf "%s\t%d\t%d\n" "$method" \
                    $(echo "$(cat {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".superstring | wc -c) * 2" | bc) \
                    $(echo "$(stat -c%s {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".mask.efe) * 8" | bc ) \
                    >> {{output}}.tmp
            done

            for method in {" ".join(COUNT_METHODS)}; do
                LENGTH=-1
                RUNS=-1
                if [[ "$method" == *"length"* ]]; then
                    LENGTH="$(head -n 1 {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".txt)"
                fi
                if [[ "$method" == *"count"* ]]; then
                    RUNS="$(head -n 1 {SUPERSTRINGS}/{{wildcards.dataset}}/{{wildcards.k}}/"$method".txt)"
                fi

                printf "%s\t%d\t%d\n" "$method" "$LENGTH" "$RUNS" >> {{output}}.tmp
            done

            echo "method\tsuperstring\tmask" > {{output}}
            sort {{output}}.tmp >> {{output}}
            rm {{output}}.tmp
        """
